version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: midas_database
    environment:
      POSTGRES_USER: adm
      POSTGRES_PASSWORD: midas
      POSTGRES_DB: midas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
