spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/midas
      username: adm
      password: midas
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

jwt:
    secret: aP9sK4lZmQ5uT3wV8nX2bZ7cE6jY1pFgR5hV9kW2oB8mG2dP6yR7nK3vW4tC9lJgP2xQ8sJ7vD6nM9baP9sK4lZmQ5uT3wV8nX2bZ7cE6jY1pFgR5hV9kW2oB8mG2dP6yR7nK3vW4tC9lJgP2xQ8sJ7vD6nM9b

